// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suydwknvkemjimblgnrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1eWR3a252a2VtamltYmxnbnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTI5NjYsImV4cCI6MjA2MTA2ODk2Nn0.demaRODnwcJRBLkIJC2vJ-zhAxLII32IjfGyl2A2eFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);